# Generated by Django 4.2.9 on 2024-03-14 04:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.PositiveIntegerField()),
                ('last_stage_modified', models.PositiveIntegerField()),
                ('stage', models.PositiveIntegerField()),
                ('probability', models.PositiveIntegerField()),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.leads')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deals',
                'verbose_name_plural': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='DefaultDealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Default deal category',
                'verbose_name_plural': 'Default deal category',
            },
        ),
        migrations.CreateModel(
            name='DefaultDealStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('probability', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultDealFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='fields')),
                ('display_name', models.CharField(max_length=35)),
                ('mem_variable', models.CharField(max_length=20)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
                ('regex_field', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_quick', models.BooleanField(default=False)),
                ('is_static', models.BooleanField(default=False)),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.defaultdealcategory')),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deals')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.fieldtype')),
            ],
            options={
                'verbose_name': 'Default deal field',
                'verbose_name_plural': 'Default Deal field',
            },
        ),
    ]
