# Generated by Django 4.1.13 on 2024-03-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_defaultdealfields_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultdealfields',
            name='icon',
        ),
    ]
