# Generated by Django 5.0.2 on 2024-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_defaultdealfields_required_alter_deals_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='stage',
            field=models.CharField(),
        ),
    ]
