# Generated by Django 5.0.2 on 2024-03-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_deals_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='owner',
            new_name='created_by',
        ),
    ]
