# Generated by Django 4.1.13 on 2024-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_fieldtype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='field_icons'),
        ),
    ]
