# Generated by Django 4.2.9 on 2024-02-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_organizationbranch_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationbranch',
            name='owner',
        ),
    ]
