# Generated by Django 4.1.13 on 2024-03-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_fieldtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='associate_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_customer_associatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='platform_customer_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
