# Generated by Django 4.2.9 on 2024-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_remove_organizationbranch_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcustomer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
