# Generated by Django 4.1.13 on 2024-03-15 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_organization_associate_by_alter_organization_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='associate_by',
        ),
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.organization')),
            ],
        ),
    ]
