# Generated by Django 4.2.9 on 2024-02-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_platformcustomer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcustomer',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
