# Generated by Django 4.2.9 on 2024-02-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcustomer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
