# Generated by Django 4.2.9 on 2024-03-14 04:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('last_modified_at', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.organization')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='DefaultCompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Default company category',
                'verbose_name_plural': 'Default company category',
            },
        ),
        migrations.CreateModel(
            name='DefaultCompanyFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='fields')),
                ('display_name', models.CharField(max_length=35)),
                ('mem_variable', models.CharField(max_length=20)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
                ('regex_field', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_quick', models.BooleanField(default=False)),
                ('is_static', models.BooleanField(default=False)),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.defaultcompanycategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.fieldtype')),
            ],
            options={
                'verbose_name': 'Default Company field',
                'verbose_name_plural': 'Default Company field',
            },
        ),
    ]
