# Generated by Django 4.1.13 on 2024-03-19 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_defaultcompanyfields_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcompanyfields',
            name='display_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='defaultcompanyfields',
            name='mem_variable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='defaultcompanyfields',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=900), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='defaultcompanyfields',
            name='regex_field',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
