# Generated by Django 5.0.2 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_defaultcompanyfields_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcompanyfields',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
