# Generated by Django 4.1.13 on 2024-03-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_defaultcustomerfields_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcustomerfields',
            name='icon',
        ),
    ]
