# Generated by Django 4.1.13 on 2024-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_defaultcustomerfields_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
