# Generated by Django 5.0.2 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_defaultcustomerfields_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcustomerfields',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
