# Generated by Django 4.2.9 on 2024-03-14 04:46

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Default lead category',
                'verbose_name_plural': 'Default lead category',
            },
        ),
        migrations.CreateModel(
            name='DefaultLeadFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='fields')),
                ('display_name', models.CharField(max_length=35)),
                ('mem_variable', models.CharField(max_length=20)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('regex_field', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_quick', models.BooleanField(default=False)),
                ('is_static', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Default lead field',
                'verbose_name_plural': 'Default lead field',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('last_modified_at', models.PositiveIntegerField()),
                ('converted_to_customer', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
