# Generated by Django 4.2.9 on 2024-03-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultleadfields',
            name='lead',
        ),
    ]
