# Generated by Django 4.1.13 on 2024-03-16 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0004_alter_leads_company_alter_leads_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultleadfields',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None),
        ),
    ]
