# Generated by Django 4.1.13 on 2024-03-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0005_alter_defaultleadfields_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='source',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='status',
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
        migrations.DeleteModel(
            name='LeadStatus',
        ),
    ]
