# Generated by Django 4.1.13 on 2024-03-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0006_remove_leads_source_remove_leads_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultleadfields',
            name='icon',
        ),
    ]
