# Generated by Django 5.0.2 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0009_remove_leads_converted_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultleadfields',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
